const express = require('express')

const weeklyRoundupRoutes = require('./weeklyRoundup')
const smartBriefingRoutes = require('./smartBriefingRoutes')
const enforcementRoutes = require('./api/enforcement')
const { router: publicationsRoutes } = require('./api/publications')

const registerAnalyticsRoutes = require('./api/analytics')
const registerAnnotationRoutes = require('./api/annotations')
const registerReportRoutes = require('./api/reports')
const registerWorkspaceRoutes = require('./api/workspace')
const registerUpdateRoutes = require('./api/updates')
const registerAiRoutes = require('./api/ai')
const registerSystemRoutes = require('./api/system')
const registerMiscRoutes = require('./api/misc')
const registerIntelligenceRoutes = require('./api/intelligence')
const registerProfileRoutes = require('./api/profile')
const registerWorkflowRoutes = require('./api/workflows')
const registerBusinessLineProfileRoutes = require('./api/businessLineProfiles')
const registerRegulatoryChangeRoutes = require('./api/regulatoryChanges')
const registerWatchListRoutes = require('./api/watchLists')
const registerDossierRoutes = require('./api/dossiers')
const registerPolicyRoutes = require('./api/policies')
const registerNotificationRoutes = require('./api/notifications')
const registerLinkedItemsRoutes = require('./api/linkedItems')
const registerAuthRoutes = require('./api/auth')
const registerFirmPersonaRoutes = require('./api/firmPersonas')
const registerCalendarRoutes = require('./api/calendar')
const registerHandbookRoutes = require('./api/handbook')
const registerInternationalRoutes = require('./api/international')
const registerDearCeoRoutes = require('./api/dearCeo')
const consultationsRoutes = require('./api/consultations')
const registerBankNewsRoutes = require('./api/bankNews')

const router = express.Router()

router.use('/', weeklyRoundupRoutes)
router.use('/', smartBriefingRoutes)
router.use('/enforcement', enforcementRoutes)
router.use('/publications', publicationsRoutes)

registerAnalyticsRoutes(router)
registerAnnotationRoutes(router)
registerReportRoutes(router)
registerWorkspaceRoutes(router)
registerUpdateRoutes(router)
registerAiRoutes(router)
registerSystemRoutes(router)
registerMiscRoutes(router)
registerIntelligenceRoutes(router)
registerProfileRoutes(router)
registerWorkflowRoutes(router)
registerBusinessLineProfileRoutes(router)
registerRegulatoryChangeRoutes(router)
registerWatchListRoutes(router)
registerDossierRoutes(router)
registerPolicyRoutes(router)
registerNotificationRoutes(router)
registerLinkedItemsRoutes(router)
registerAuthRoutes(router)
registerFirmPersonaRoutes(router)
registerCalendarRoutes(router)
registerHandbookRoutes(router)
registerInternationalRoutes(router)
registerDearCeoRoutes(router)
router.use('/consultations', consultationsRoutes)
registerBankNewsRoutes(router)

module.exports = router
