const express = require('express')

const renderHomePage = require('./pages/homePage')
const { renderDashboardPage } = require('./pages/dashboardPage')
const renderAnalyticsPage = require('./pages/analyticsPage')
const renderEnforcementPage = require('./pages/enforcementPage')
const renderWeeklyBriefingPage = require('./pages/weeklyBriefingPage')
const renderUpdateDetailPage = require('./pages/updateDetailPage')
const renderAiIntelligencePage = require('./pages/aiIntelligence')
const renderAiIntelligenceExportPage = require('./pages/aiIntelligence/exportPage')
const renderAiIntelligenceExportPdfPage = require('./pages/aiIntelligence/exportPdfPage')
const renderAuthoritySpotlightPage = require('./pages/authoritySpotlightPage')
const renderSectorIntelligencePage = require('./pages/sectorIntelligencePage')
const renderAboutPage = require('./pages/aboutPage')
const renderTestPage = require('./pages/testPage')
const { renderKanbanPage } = require('./pages/kanbanPage')
const { renderRegulatoryAnalyticsPage } = require('./pages/regulatoryAnalyticsPage')

const router = express.Router()

router.get('/', renderHomePage)
router.get('/dashboard', renderDashboardPage)
router.get('/analytics', renderAnalyticsPage)
router.get('/enforcement', renderEnforcementPage)
router.get('/update/:id', renderUpdateDetailPage)
router.get('/weekly-roundup', renderWeeklyBriefingPage)
router.get('/ai-intelligence', renderAiIntelligencePage)
router.get('/ai-intelligence/export/one-pager', renderAiIntelligenceExportPage)
router.get('/ai-intelligence/export/one-pager.pdf', renderAiIntelligenceExportPdfPage)
router.get('/authority-spotlight/:authority?', (req, res) =>
  renderAuthoritySpotlightPage(req, res, req.params.authority || 'FCA')
)
router.get('/sector-intelligence/:sector?', (req, res) =>
  renderSectorIntelligencePage(req, res, req.params.sector || 'Banking')
)
router.get('/about', renderAboutPage)
router.get('/test', renderTestPage)
router.get('/kanban', renderKanbanPage)
router.get('/regulatory-changes', renderKanbanPage)
router.get('/regulatory-analytics', renderRegulatoryAnalyticsPage)

module.exports = router
