const { getPublicationsStyles } = require('./assets')

/**
 * Renders the Annual Enforcement Summary page
 * Beautiful typography, professional prose layout
 */
function renderSummaryPage({
  sidebar,
  commonStyles,
  commonClientScripts,
  year,
  summary = null,
  stats = null
}) {
  const hasData = stats && stats.totalActions > 0
  const hasSummary = summary && summary.summary_html

  return `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>FCA Enforcement Summary ${year} - RegCanary</title>
        ${commonStyles}
        ${getPublicationsStyles()}
        <link rel="stylesheet" href="/css/publications/summary.css">
        <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&family=Source+Sans+Pro:wght@400;600&display=swap" rel="stylesheet">
      </head>
      <body>
        <div class="app-container">
          ${sidebar}
          <main class="main-content summary-page">
            <!-- Back Navigation -->
            <div class="summary-nav">
              <a href="/publications" class="back-link">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <path d="M19 12H5M12 19l-7-7 7-7"/>
                </svg>
                Back to Regulatory Notices
              </a>
              <div class="summary-actions">
                <button class="action-btn print-btn" onclick="window.print()">
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="M6 9V2h12v7M6 18H4a2 2 0 01-2-2v-5a2 2 0 012-2h16a2 2 0 012 2v5a2 2 0 01-2 2h-2"/>
                    <rect x="6" y="14" width="12" height="8"/>
                  </svg>
                  Print
                </button>
                <button class="action-btn regenerate-btn" id="regenerate-btn" ${!hasData ? 'disabled' : ''}>
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="M21.5 2v6h-6M2.5 22v-6h6M2 11.5a10 10 0 0118.8-4.3M22 12.5a10 10 0 01-18.8 4.2"/>
                  </svg>
                  <span id="regenerate-text">${hasSummary ? 'Regenerate Summary' : 'Generate Summary'}</span>
                </button>
              </div>
            </div>

            <!-- Summary Document -->
            <article class="summary-document">
              <!-- Document Header -->
              <header class="summary-header">
                <div class="document-badge">FCA Enforcement Activity</div>
                <h1 class="summary-year">${year}</h1>
                <div class="summary-meta">
                  ${stats ? `
                    <span class="meta-item">
                      <strong>${(stats.totalActions || 0).toLocaleString()}</strong> enforcement actions
                    </span>
                    <span class="meta-divider">|</span>
                    <span class="meta-item">
                      <strong>${formatCurrency(stats.totalFines || 0)}</strong> in penalties
                    </span>
                  ` : ''}
                  ${hasSummary ? `
                    <span class="meta-divider">|</span>
                    <span class="meta-item generated-at">
                      Generated ${formatDate(summary.generated_at)}
                    </span>
                  ` : ''}
                </div>
              </header>

              <!-- Summary Content -->
              <div class="summary-content" id="summary-content">
                ${hasSummary ? summary.summary_html : renderPlaceholder(hasData, year)}
              </div>

              <!-- Footer -->
              <footer class="summary-footer">
                <p class="disclaimer">
                  This summary is generated by AI analysis of FCA enforcement notices and should be used
                  for informational purposes only. Always refer to official FCA publications for authoritative guidance.
                </p>
                <div class="footer-branding">
                  <span>Powered by RegCanary</span>
                  <span class="footer-dot"></span>
                  <span>Horizon Scanning Intelligence</span>
                </div>
              </footer>
            </article>

            <!-- Year Navigation -->
            <nav class="year-navigation">
              <a href="/publications/summary/${year - 1}" class="year-nav-link prev">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <path d="M15 18l-6-6 6-6"/>
                </svg>
                ${year - 1}
              </a>
              ${year < new Date().getFullYear() ? `
                <a href="/publications/summary/${year + 1}" class="year-nav-link next">
                  ${year + 1}
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="M9 18l6-6-6-6"/>
                  </svg>
                </a>
              ` : '<span></span>'}
            </nav>
          </main>
        </div>
        ${commonClientScripts}
        <script>
          window.SUMMARY_YEAR = ${year};
          window.HAS_SUMMARY = ${hasSummary};
        </script>
        <script src="/js/publications/summary.js"></script>
      </body>
    </html>
  `
}

function renderPlaceholder(hasData, year) {
  if (!hasData) {
    return `
      <div class="summary-placeholder empty">
        <svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
          <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/>
          <path d="M14 2v6h6M16 13H8M16 17H8M10 9H8"/>
        </svg>
        <h3>No Data Available</h3>
        <p>There are no enforcement notices recorded for ${year}.</p>
      </div>
    `
  }

  return `
    <div class="summary-placeholder">
      <svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
        <path d="M12 2a10 10 0 1010 10A10 10 0 0012 2z"/>
        <path d="M12 6v6l4 2"/>
      </svg>
      <h3>Summary Not Yet Generated</h3>
      <p>Click "Generate Summary" to create an AI-powered analysis of ${year} enforcement activity.</p>
      <p class="placeholder-note">The summary will include an overview, enforcement landscape analysis, significant cases, recurring themes, and key takeaways for compliance teams.</p>
    </div>
  `
}

function formatCurrency(amount) {
  if (!amount || amount === 0) return '£0'
  if (amount >= 1000000000) {
    return '£' + (amount / 1000000000).toFixed(1) + 'B'
  }
  if (amount >= 1000000) {
    return '£' + (amount / 1000000).toFixed(1) + 'M'
  }
  if (amount >= 1000) {
    return '£' + (amount / 1000).toFixed(1) + 'K'
  }
  return '£' + amount.toLocaleString()
}

function formatDate(dateStr) {
  if (!dateStr) return ''
  const date = new Date(dateStr)
  return date.toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  })
}

module.exports = {
  renderSummaryPage
}
